### ISSUE TITLE
Breaks terminal scrolling on Mac OS X

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/bwallet#17]
Unable to scroll back to view earlier terminal history using the 2 finger scroll gesture (this normally works in terminal).  Instead of scrolling, the lots of characters appear in the wallet command prompt. (see screenshot)

<img width="1180" alt="screen shot 2015-08-09 at 2 17 16 pm" src="https://cloud.githubusercontent.com/assets/597182/9153793/07a1c6c8-3ea2-11e5-8008-22584a1a8295.png">

**Comment by mflaxman** [comment]
Thanks for filing.

Hmm, I just tried on 10.10.4 and I was able to without getting those characters.

What output do you get for this?:
```
$ echo $TERM
```

If nothing (TERM value not set), try this:
```
$ export TERM=xterm-256color
```

If that doesn't solve it, it could be a lot of things that are somewhat hard to pinpoint. What's tricky is that the app is using the character mappings that your terminal is configured for at runtime, so it's not exactly a bug per say. But the fact that your terminal is behaving differently for this app vs others is kind of a bug. It could have to do with pip, your bash settings, or something else. This one may be tricky to figure out.

**Comment by larrysalibra** [comment]
I'm using 10.11 beta 6 (build 15A244d). I can't replicate right now either. Now that I think about it, I may have gotten overzealous with the entropy generating keyboard banging and hit some key combination that messed up a terminal setting.  I'll re-open if I figure out how to replicate.
